const TAX = 0.2;
const SHIPPING_LIMIT = 50;
const SHIP = 5.0;
const PREMIUM_THRESHOLD = 1000;
const LOYALTY_RATIO = 0.01;
const HANDLING_FEE = 2.5;
const MAX_DISCOUNT = 200;

export {
  TAX,
  SHIPPING_LIMIT,
  SHIP,
  PREMIUM_THRESHOLD,
  LOYALTY_RATIO,
  HANDLING_FEE,
  MAX_DISCOUNT,
};
